### ISSUE TITLE
"Get an issue remote links" example not working

### ISSUE THREAD

**Issue by zedtux** [steves/node-jira#100]
After having installed `node-jira` and created the Jira client I tried both:
- Find the status of an issue
- Get an issue remote links

While the first one works fine, the second one is failing with the following:

```
TypeError: undefined is not a function
    at repl:1:6
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
```

**Comment by zedtux** [comment]
I have noticed that working functions are written as the following:

```javascript
    this.issueLink = function(link, callback) {
      // ...
    }
```

while [this one](https://github.com/steves/node-jira/blob/master/lib/jira.js#L607) is written as following:

```javascript
    this.getRemoteLinks = function getRemoteLinks(issueNumber, callback) {
      // ...
    }
```

I tried to figure out what means having the function name on the `this` and after the `function` but I don't find anything.

Could it be the reason of the issue ?

**Comment by dstreet26** [comment]
I'm also having trouble getting the example to work.

```
jira.getRemoteLinks(issueNumber, function (err, issue) {
     ^

TypeError: jira.getRemoteLinks is not a function
```

Over 2 years and no comment on this?

**Comment by zedtux** [comment]
I guess it is no more maintained... closing the issue.
