### ISSUE TITLE
Problem with JQL request

### ISSUE THREAD

**Issue by kevincaradant** [steves/node-jira#114]
Hi everyone,

I'm trying to use search query but i can't have the result as i want.

i'm trying that : 

jira.searchJira(req.body.requete, null, function(test, body) {
    //console.log(body);
    res.send(body);
});

and req.body.requete = "?jql=key=RAV-56" , the problem is here, all cards are returned in JSON ( 200 000 results) like if jql=' ' because by defaults if jql is empty , all the results appear , so how is it possible to success a request with jql :/. 

Thank you

**Comment by leonzinger** [comment]
@kevincaradant as it seems from source code it's jql by default, just remove the jql= from your query

**Comment by kevincaradant** [comment]
Sorry i totally forgot to answer you. I close this issue, thank you for your answer ;)
