### ISSUE TITLE
Request from behind corporate proxy

### ISSUE THREAD

**Issue by romosch** [steves/node-jira#136]
I get the following error when using the listProjects function:
Error: connect EHOSTUNREACH (some IP address X)

I have seen this EHOSTUNREACH message before and it was caused by being behind a corporate proxy.
Is there a way of giving in proxy details to fix this (like the --proxy flag from curl)?

Cheers

**Comment by gorootde** [comment]
I fixed this by forking the project and using the newest version of "request" module
